# -*- coding: utf-8 -*-
"""ML_Assignment_1_Chetan_Pant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eF9sCWwCOV7ky594sv1vnc-7D8S5eNvO

## Step 0: Load Dataset from Kaggle in Google Colab
"""

# Install kagglehub
!pip install kagglehub

# Import library
import kagglehub
import pandas as pd

# Download dataset
path = kagglehub.dataset_download("redwankarimsony/heart-disease-data")

print("Dataset path:", path)

# Load the CSV file
df = pd.read_csv(path + "/heart_disease_uci.csv")

# Preview data
df.head()

"""## Task A — Data Quality and Preprocessing

### A1 — Identify Missing Values, Duplicates, and Outliers
"""

# Shape of dataset
df.shape

# Column names
df.columns

# Data types
df.dtypes

df.isnull().sum()

df.duplicated().sum()

df = df.drop_duplicates()

import matplotlib.pyplot as plt
import seaborn as sns

numeric_cols = df.select_dtypes(include=['int64','float64']).columns

plt.figure(figsize=(15,8))
for i, col in enumerate(numeric_cols):
    plt.subplot(3,5,i+1)
    sns.boxplot(y=df[col])
    plt.title(col)

plt.tight_layout()
plt.show()

"""### A2 — Attribute Types

| Feature              | Attribute Type       |
| -------------------- | -------------------- |
| age                  | Numeric (Continuous) |
| sex                  | Nominal              |
| dataset              | Nominal              |
| cp (chest pain type) | Nominal              |
| trestbps             | Numeric (Continuous) |
| chol                 | Numeric (Continuous) |
| fbs                  | Nominal              |
| restecg              | Nominal              |
| thalch               | Numeric (Continuous) |
| exang                | Nominal              |
| oldpeak              | Numeric (Continuous) |
| slope                | Ordinal              |
| ca                   | Numeric (Discrete)   |
| thal                 | Nominal              |
| num                  | Target variable      |

### A3 — Data Preprocessing
"""

df = df.drop(columns=['id'], errors='ignore')

df['num'] = df['num'].apply(lambda x: 0 if x==0 else 1)

from sklearn.impute import SimpleImputer

num_cols = df.select_dtypes(include=['int64','float64']).columns

imputer = SimpleImputer(strategy='median')
df[num_cols] = imputer.fit_transform(df[num_cols])

cat_cols = df.select_dtypes(include=['object']).columns

imputer_cat = SimpleImputer(strategy='most_frequent')
df[cat_cols] = imputer_cat.fit_transform(df[cat_cols])

df = pd.get_dummies(df, columns=cat_cols, drop_first=True)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X = df.drop('num', axis=1)
y = df['num']

X_scaled = scaler.fit_transform(X)

"""### A4 — Train Test Split"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

"""## Task B — Model Training + Evaluation"""

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    roc_curve
)

import matplotlib.pyplot as plt
import seaborn as sns

log_model = LogisticRegression(max_iter=1000)

log_model.fit(X_train, y_train)

y_pred_log = log_model.predict(X_test)
y_prob_log = log_model.predict_proba(X_test)[:,1]

cm_log = confusion_matrix(y_test, y_pred_log)

plt.figure(figsize=(5,4))
sns.heatmap(cm_log, annot=True, fmt="d", cmap="Blues")
plt.title("Confusion Matrix - Logistic Regression")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

accuracy_log = accuracy_score(y_test, y_pred_log)
precision_log = precision_score(y_test, y_pred_log)
recall_log = recall_score(y_test, y_pred_log)
f1_log = f1_score(y_test, y_pred_log)
roc_auc_log = roc_auc_score(y_test, y_prob_log)

print("Logistic Regression Performance")
print("Accuracy:", accuracy_log)
print("Precision:", precision_log)
print("Recall:", recall_log)
print("F1 Score:", f1_log)
print("ROC AUC:", roc_auc_log)

nb_model = GaussianNB()

nb_model.fit(X_train, y_train)

y_pred_nb = nb_model.predict(X_test)
y_prob_nb = nb_model.predict_proba(X_test)[:,1]

cm_nb = confusion_matrix(y_test, y_pred_nb)

plt.figure(figsize=(5,4))
sns.heatmap(cm_nb, annot=True, fmt="d", cmap="Greens")
plt.title("Confusion Matrix - Naive Bayes")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

accuracy_nb = accuracy_score(y_test, y_pred_nb)
precision_nb = precision_score(y_test, y_pred_nb)
recall_nb = recall_score(y_test, y_pred_nb)
f1_nb = f1_score(y_test, y_pred_nb)
roc_auc_nb = roc_auc_score(y_test, y_prob_nb)

print("Naive Bayes Performance")
print("Accuracy:", accuracy_nb)
print("Precision:", precision_nb)
print("Recall:", recall_nb)
print("F1 Score:", f1_nb)
print("ROC AUC:", roc_auc_nb)

import pandas as pd

results = pd.DataFrame({
    "Model": ["Logistic Regression", "Naive Bayes"],
    "Accuracy": [accuracy_log, accuracy_nb],
    "Precision": [precision_log, precision_nb],
    "Recall": [recall_log, recall_nb],
    "F1 Score": [f1_log, f1_nb],
    "ROC AUC": [roc_auc_log, roc_auc_nb]
})

results

"""## Task C - Decision Tree Learning + Interpretation"""

from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import plot_tree

dt_model = DecisionTreeClassifier(random_state=42)

dt_model.fit(X_train, y_train)

dt_model = DecisionTreeClassifier(
    max_depth=4,
    min_samples_split=10,
    min_samples_leaf=5,
    random_state=42
)

dt_model.fit(X_train, y_train)

y_pred_dt = dt_model.predict(X_test)
y_prob_dt = dt_model.predict_proba(X_test)[:,1]

from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

cm_dt = confusion_matrix(y_test, y_pred_dt)

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(5,4))
sns.heatmap(cm_dt, annot=True, fmt="d", cmap="Oranges")
plt.title("Confusion Matrix - Decision Tree")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

accuracy_dt = accuracy_score(y_test, y_pred_dt)
precision_dt = precision_score(y_test, y_pred_dt)
recall_dt = recall_score(y_test, y_pred_dt)
f1_dt = f1_score(y_test, y_pred_dt)
roc_auc_dt = roc_auc_score(y_test, y_prob_dt)

print("Decision Tree Performance")
print("Accuracy:", accuracy_dt)
print("Precision:", precision_dt)
print("Recall:", recall_dt)
print("F1 Score:", f1_dt)
print("ROC AUC:", roc_auc_dt)

import pandas as pd

feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': dt_model.feature_importances_
})

feature_importance = feature_importance.sort_values(by='Importance', ascending=False)

feature_importance

plt.figure(figsize=(10,6))
sns.barplot(x='Importance', y='Feature', data=feature_importance)
plt.title("Feature Importance - Decision Tree")
plt.show()

plt.figure(figsize=(20,10))

plot_tree(
    dt_model,
    feature_names=X.columns,
    class_names=["No Disease","Disease"],
    filled=True
)

plt.show()

"""## Task D - Rule-Based Classification"""

from sklearn.tree import export_text

tree_rules = export_text(dt_model, feature_names=list(X.columns))

print(tree_rules)

"""## Task E - kNN (Lazy Learning)  """

from sklearn.neighbors import KNeighborsClassifier

k_values = [1,3,5,7,9]

knn_results = []

for k in k_values:

    knn_model = KNeighborsClassifier(n_neighbors=k)

    knn_model.fit(X_train, y_train)

    y_pred = knn_model.predict(X_test)
    y_prob = knn_model.predict_proba(X_test)[:,1]

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    roc = roc_auc_score(y_test, y_prob)

    knn_results.append([k, acc, prec, rec, f1, roc])

knn_results_df = pd.DataFrame(knn_results, columns=[
    "k",
    "Accuracy",
    "Precision",
    "Recall",
    "F1 Score",
    "ROC AUC"
])

knn_results_df

metrics = ["euclidean","manhattan"]

metric_results = []

for metric in metrics:

    knn_model = KNeighborsClassifier(
        n_neighbors=5,
        metric=metric
    )

    knn_model.fit(X_train, y_train)

    y_pred = knn_model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)

    metric_results.append([metric, acc])

metric_results_df = pd.DataFrame(metric_results, columns=[
    "Distance Metric",
    "Accuracy"
])

metric_results_df

import matplotlib.pyplot as plt

plt.plot(knn_results_df["k"], knn_results_df["Accuracy"], marker="o")
plt.xlabel("k value")
plt.ylabel("Accuracy")
plt.title("Accuracy vs k")
plt.show()

"""## Task F - Ensemble Learning"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import AdaBoostClassifier

rf_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=5,
    random_state=42
)

rf_model.fit(X_train, y_train)

y_pred_rf = rf_model.predict(X_test)
y_prob_rf = rf_model.predict_proba(X_test)[:,1]

accuracy_rf = accuracy_score(y_test, y_pred_rf)
precision_rf = precision_score(y_test, y_pred_rf)
recall_rf = recall_score(y_test, y_pred_rf)
f1_rf = f1_score(y_test, y_pred_rf)
roc_rf = roc_auc_score(y_test, y_prob_rf)

print("Random Forest Performance")
print("Accuracy:", accuracy_rf)
print("Precision:", precision_rf)
print("Recall:", recall_rf)
print("F1 Score:", f1_rf)
print("ROC AUC:", roc_rf)

gb_model = GradientBoostingClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=42
)

gb_model.fit(X_train, y_train)

y_pred_gb = gb_model.predict(X_test)
y_prob_gb = gb_model.predict_proba(X_test)[:,1]

accuracy_gb = accuracy_score(y_test, y_pred_gb)
precision_gb = precision_score(y_test, y_pred_gb)
recall_gb = recall_score(y_test, y_pred_gb)
f1_gb = f1_score(y_test, y_pred_gb)
roc_gb = roc_auc_score(y_test, y_prob_gb)

print("Gradient Boosting Performance")
print("Accuracy:", accuracy_gb)
print("Precision:", precision_gb)
print("Recall:", recall_gb)
print("F1 Score:", f1_gb)
print("ROC AUC:", roc_gb)

ada_model = AdaBoostClassifier(
    n_estimators=100,
    random_state=42
)

ada_model.fit(X_train, y_train)

y_pred_ada = ada_model.predict(X_test)

accuracy_ada = accuracy_score(y_test, y_pred_ada)

print("AdaBoost Accuracy:", accuracy_ada)

comparison = pd.DataFrame({
    "Model":[
        "Logistic Regression",
        "Naive Bayes",
        "Decision Tree",
        "kNN",
        "Random Forest",
        "Gradient Boosting"
    ],

    "Accuracy":[
        accuracy_log,
        accuracy_nb,
        accuracy_dt,
        knn_results_df["Accuracy"].max(),
        accuracy_rf,
        accuracy_gb
    ]
})

comparison

"""## Task G - Final Comparison + Recommendation"""

final_results = pd.DataFrame({
    "Model":[
        "Logistic Regression",
        "Naive Bayes",
        "Decision Tree",
        "kNN (k=7)",
        "Random Forest",
        "Gradient Boosting"
    ],

    "Accuracy":[
        accuracy_log,
        accuracy_nb,
        accuracy_dt,
        knn_results_df["Accuracy"].max(),
        accuracy_rf,
        accuracy_gb
    ],

    "F1 Score":[
        f1_log,
        f1_nb,
        f1_dt,
        knn_results_df["F1 Score"].max(),
        f1_rf,
        f1_gb
    ],

    "Notes":[
        "Baseline linear model",
        "Probabilistic baseline classifier",
        "Interpretable rule-based tree",
        "Distance-based lazy learner",
        "Ensemble of decision trees",
        "Boosting ensemble model"
    ]
})

final_results





